# Generated by Django 4.1.4 on 2023-01-02 14:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('hospital_entry_date', models.DateField(blank=True, null=True)),
                ('hospital_release_date', models.DateField(blank=True, null=True)),
                ('medical_history', models.TextField(blank=True, default='')),
                ('medical_condition', models.TextField(blank=True, default='')),
                ('surgery_processes', models.TextField(blank=True, default='')),
                ('medication', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('hospital_entry_date', models.DateField(blank=True, null=True)),
                ('hospital_release_date', models.DateField(blank=True, null=True)),
                ('medical_history', models.TextField(blank=True, default='')),
                ('medical_condition', models.TextField(blank=True, default='')),
                ('surgery_processes', models.TextField(blank=True, default='')),
                ('medication', models.TextField(blank=True, default='')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
    ]
