# Generated by Django 4.1.4 on 2022-12-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('published', models.DateTimeField()),
                ('information', models.TextField()),
                ('contributor', models.ManyToManyField(to='users.appuser')),
            ],
        ),
    ]
