# Generated by Django 4.1.4 on 2022-12-29 12:22

from django.db import migrations, models
import medic.models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMedicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('published', models.DateTimeField()),
                ('doctors', models.CharField(max_length=300)),
                ('patient', models.CharField(max_length=300)),
                ('information', models.JSONField(default=medic.models.empty_dict)),
            ],
        ),
        migrations.AlterField(
            model_name='medicreport',
            name='information',
            field=models.JSONField(default=medic.models.empty_dict),
        ),
    ]
